# Generated by Django 3.1.6 on 2021-02-26 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(default='This is the summary of your article.', max_length=240)),
                ('body', models.TextField()),
                ('img_link', models.CharField(default='/static/images/summary/jpg', max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='BigCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Big category')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='Personal website', help_text='description', max_length=240)),
                ('keywords', models.TextField(default='Django, Blog', help_text='keywords', max_length=240)),
            ],
            options={
                'verbose_name': 'big category',
                'verbose_name_plural': 'big categories',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Number determines the playing order')),
                ('title', models.CharField(blank=True, help_text='Title can be NULL', max_length=100, null=True)),
                ('content', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=200)),
                ('url', models.CharField(default='#', help_text='Hyperlink for image jump. #: no jumping.', max_length=200)),
            ],
            options={
                'ordering': ['number', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField()),
                ('logo', models.URLField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_show', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Keyword')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Tag')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='Personal website', help_text='description', max_length=240)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Article category')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='Personal website', help_text='description', max_length=240)),
                ('bigcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.bigcategory', verbose_name='Big category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
